import User_Survey_Class

def main():

    ## Defining an object from the class defined in original

    myUser = User_Survey_Class.UserSurvey()

    """Functions that use object defined above and the get
    functions defined in User_Survey_Class to print values"""

    print(myUser.get_survey_id())
    print(myUser.get_survey_submitted_at())
    print(myUser.get_trip_start_date())
    print(myUser.get_trip_finish_date())
    print(myUser.get_hotel_name())
    print(myUser.get_hotel_code())
    print(myUser.get_hotel_trip_other_name())
    print(myUser.get_hotel_any_other())
    print(myUser.get_hotel_ritz_carlton())
    print(myUser.get_hotel_super_eight())
    print(myUser.get_hotel_embassy_suites())
    print(myUser.get_hotel_days_inn())
    print(myUser.get_hotel_hampton_inn())
    print(myUser.get_hotel_quality_inn())
    print(myUser.get_hotel_marriott())
    print(myUser.get_hotel_holiday_inn())
    print(myUser.get_hotel_omni())
    print(myUser.get_hotel_hilton())
    print(myUser.get_hotel_millenium())
    print(myUser.get_hotel_radisson())
    print(myUser.get_hotel_hyatt())
    print(myUser.get_hotel_fairfield_inn())
    print(myUser.get_hotel_ramada_inn())
    print(myUser.get_hotel_drury_inn())
    print(myUser.get_hotel_four_seasons())
    print(myUser.get_hotel_best_western())
    print(myUser.get_hotel_past_other_name())
    print(myUser.get_hotel_selection_cost())
    print(myUser.get_hotel_selection_bar())
    print(myUser.get_hotel_selection_distance_to_parks())
    print(myUser.get_hotel_selection_in_room_dining())
    print(myUser.get_hotel_selection_food_court())
    print(myUser.get_hotel_selection_sit_down_dining())
    print(myUser.get_hotel_selection_fine_dining())
    print(myUser.get_hotel_selection_parks_shuttle())
    print(myUser.get_hotel_selection_airport_shuttle())
    print(myUser.get_hotel_selection_in_room_kitchen())
    print(myUser.get_hotel_selection_room_size())
    print(myUser.get_hotel_selection_multiple_bedroom_suites())
    print(myUser.get_hotel_selection_spa_fitness_center())
    print(myUser.get_hotel_selection_pool())
    print(myUser.get_hotel_selection_theme())
    print(myUser.get_hotel_selection_kids_activities())
    print(myUser.get_hotel_selection_location_on_property())
    print(myUser.get_hotel_selection_other_string())
    print(myUser.get_hotel_selection_other_rating())
    print(myUser.get_hotel_satisfied_room_cleanliness())
    print(myUser.get_hotel_satisfied_room_size())
    print(myUser.get_hotel_satisfied_room_quietness())
    print(myUser.get_hotel_satisfied_beds_pillows())
    print(myUser.get_hotel_satisfied_pool_size())
    print(myUser.get_hotel_satisfied_pool_crowds())
    print(myUser.get_hotel_satisfied_pool_cleanliness())
    print(myUser.get_hotel_satisfied_parks_shuttle())
    print(myUser.get_hotel_satisfied_airport_shuttle())
    print(myUser.get_hotel_satisfied_check_in_out_process())
    print(myUser.get_hotel_satisfied_staff())
    print(myUser.get_hotel_satisfied_recreation_amenities())
    print(myUser.get_hotel_satisfied_food_court_overall())
    print(myUser.get_hotel_satisfied_food_court_value())
    print(myUser.get_hotel_satisfied_find_your_way_around())
    print(myUser.get_hotel_satisfied_child_services())
    print(myUser.get_hotel_satisfied_sit_down_dining())
    print(myUser.get_hotel_satisfied_other_string())
    print(myUser.get_hotel_satisfied_other_rating())
    print(myUser.get_hotel_satisfaction_code())
    print(myUser.get_hotel_stay_again())
    print(myUser.get_hotel_recommendation_code())
    print(myUser.get_hotel_room_number())
    print(myUser.get_hotel_room_connecting())
    print(myUser.get_hotel_room_connecting_room_number())
    print(myUser.get_hotel_room_bed_code())
    print(myUser.get_user_id())
    print(myUser.get_party_members())
    print(myUser.get_hometown())
    print(myUser.get_how_many_trips())
    print(myUser.get_ip_address())

    print(myUser.buildListWriteCSV())


main()
    
